// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RngGenetics.Data;

#nullable disable

namespace RngGenetics.Migrations
{
    [DbContext(typeof(EFCoreTestContext))]
    [Migration("20231126160037_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RngGenetics.Models.SboxFourBits", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DifferentialUniformity")
                        .HasColumnType("int");

                    b.Property<int>("Linearity")
                        .HasColumnType("int");

                    b.Property<string>("Sbox")
                        .HasColumnType("char(16)");

                    b.HasKey("Id");

                    b.ToTable("Sboxes");
                });
#pragma warning restore 612, 618
        }
    }
}
